import json
import logging
import re
import tarfile
import xml.etree.ElementTree as ET

import requests

from . import http
from . import prow

logger = logging.getLogger(__name__)

_AGENTS_MD_SIGNATURE = "<!-- Generated by download_prow_job.py -->"

_AGENTS_MD_CONTENT = """{signature}
# Prow CI Job Artifacts

This directory contains artifacts downloaded from Prow CI jobs.

## Directory Structure

Each subdirectory is named by build ID and may contain:

- `build_info.json` - Build metadata including:
  - `build_id`: The Prow build ID
  - `execution_date`: When the build ran (ISO 8601)
  - `prow_job_link`: Link to the Prow job page (Spyglass view)
  - `pr_link`: GitHub PR URL (if PR job)
  - `commit_link`: GitHub commit URL being tested

- `junit_operator.xml` - JUnit XML test results from the CI operator

- `build-logs/` - Artifacts for failed steps only
  - `{{step-name}}/` - One subdirectory per failed step
    - `build-log.txt` - Complete untruncated build log
    - `junit_e2e__*.xml` - Individual e2e test results (if the step produced junit output)
    - `e2e-monitor-tests__*.xml` - Monitor test results (if available)

- `must-gather/` - Extracted must-gather diagnostic data (if available)

- `hypershift-dumps/` - Extracted HyperShift hosted cluster dumps (if available)
  - `TestCreateCluster/` - Dump for each test case
  - `TestNodePool_HostedCluster0/`
  - Contains pod logs, events, and resource YAMLs from the hosted control plane

## Analyzing Test Failures

1. Check `build_info.json` for the job link and PR context
2. Parse `junit_operator.xml` to find failed CI steps
3. Read `build-logs/{{step}}/build-log.txt` for complete failure output
4. Parse `build-logs/{{step}}/junit_e2e__*.xml` for individual e2e test failures (if available)
5. For cluster issues, examine logs in `must-gather/`

## must-gather Contents

The must-gather directory contains OpenShift cluster diagnostics:
- Pod logs from key namespaces
- Cluster operator status
- Event logs
- Resource definitions

Look for errors in `must-gather/*/logs/` and check operator status in
`must-gather/*/cluster-scoped-resources/`.
"""


def fetch_step_graph(gcs_path, gcsweb_base):
    """Download and parse ci-operator-step-graph.json.
    Returns parsed list of step dicts, or None if not available.
    """
    url = f"{gcsweb_base}{gcs_path}/artifacts/ci-operator-step-graph.json"
    try:
        logger.info(f"Fetching step graph: {url}")
        response = http.session_get(url, timeout=30)
        if response.status_code == 404:
            logger.error("Step graph not found (404)")
            return None
        response.raise_for_status()
        return json.loads(response.text)
    except requests.RequestException as e:
        logger.error(f"Failed to fetch step graph: {e}")
        return None
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse step graph JSON: {e}")
        return None


def parse_junit_operator_failures(junit_path):
    """
    Parse junit_operator.xml to extract failed multi-stage test steps.
    Returns list of (test_name, inner_step_name) tuples for failed steps only.

    Test case names follow the pattern:
      "Run multi-stage test {test_name} - {test_name}-{inner_step} container test"

    The artifact directory uses inner_step (prefix stripped), not the full step name.
    """
    try:
        tree = ET.parse(junit_path)
    except (ET.ParseError, OSError) as e:
        logger.warning(f"Failed to parse {junit_path}: {e}")
        return []

    failures = []

    for tc in tree.getroot().iter("testcase"):
        if tc.find("failure") is None:
            continue
        name = tc.get("name", "")
        m = re.match(r"Run multi-stage test (\S+) - (\S+) container test", name)
        if not m:
            continue
        test_name, full_step = m.group(1), m.group(2)
        prefix = test_name + "-"
        inner_step = full_step[len(prefix):] if full_step.startswith(prefix) else full_step
        failures.append((test_name, inner_step))

    return failures


def download_failed_step_artifacts(gcs_path, gcsweb_base, failures, logs_dir):
    """
    Download build-log.txt and any junit XML files for each failed step.

    build-log.txt is at a deterministic path (no directory listing needed).
    junit files require up to 2 directory listing requests per failed step.
    """
    total = 0

    for test_name, full_step_name in failures:
        step_base = f"{gcs_path}/artifacts/{test_name}/{full_step_name}"
        dest_dir = logs_dir / full_step_name

        build_log_url = f"{gcsweb_base}{step_base}/build-log.txt"
        if http.download_artifact(build_log_url, dest_dir / "build-log.txt"):
            total += 1

        artifacts_base = f"{step_base}/artifacts"

        junit_subdir_url = f"{gcsweb_base}{artifacts_base}/junit/"
        _, files = http.list_gcsweb_dir(junit_subdir_url)
        for filename in [f for f in files if f.endswith(".xml")]:
            if http.download_artifact(f"{gcsweb_base}{artifacts_base}/junit/{filename}", dest_dir / filename):
                total += 1

        artifacts_url = f"{gcsweb_base}{artifacts_base}/"
        _, root_files = http.list_gcsweb_dir(artifacts_url)
        for filename in [f for f in root_files if f.startswith("junit") and f.endswith(".xml")]:
            if http.download_artifact(f"{gcsweb_base}{artifacts_base}/{filename}", dest_dir / filename):
                total += 1

        logger.info(f"Downloaded artifacts for failed step {full_step_name}")

    return total


def discover_must_gather(gcs_path, gcsweb_base, step_graph):
    """
    Find must-gather.tar using step graph to identify test steps.
    Returns the full GCS path to must-gather.tar if found, None otherwise.
    """
    test_steps = [s["name"] for s in step_graph if not s.get("name", "").startswith("[")]

    for step_name in test_steps:
        gather_artifacts_url = f"{gcsweb_base}{gcs_path}/artifacts/{step_name}/gather-must-gather/artifacts/"
        _, files = http.list_gcsweb_dir(gather_artifacts_url)
        if "must-gather.tar" in files:
            full_path = f"{gcs_path}/artifacts/{step_name}/gather-must-gather/artifacts/must-gather.tar"
            logger.info(f"Found must-gather at: {step_name}/gather-must-gather/artifacts/must-gather.tar")
            return full_path

    logger.info("No must-gather found in any test step")
    return None


def discover_hypershift_dumps(gcs_path, gcsweb_base, step_graph):
    """
    Find hostedcluster.tar files from steps running the HyperShift test binary.
    Uses step graph to identify relevant steps via [input:hypershift-tests] dependency.
    Returns list of (test_dir_name, gcs_tar_path) tuples, or empty list.
    """
    hypershift_steps = [
        s["name"] for s in step_graph
        if "[input:hypershift-tests]" in (s.get("dependencies") or [])
    ]

    if not hypershift_steps:
        return []

    logger.info(f"Found HyperShift test steps: {hypershift_steps}")
    results = []

    for step_name in hypershift_steps:
        step_url = f"{gcsweb_base}{gcs_path}/artifacts/{step_name}/"
        inner_subdirs, _ = http.list_gcsweb_dir(step_url)

        for inner_subdir in inner_subdirs:
            inner_artifacts_url = f"{gcsweb_base}{gcs_path}/artifacts/{step_name}/{inner_subdir}/artifacts/"
            test_subdirs, _ = http.list_gcsweb_dir(inner_artifacts_url)

            for test_dir in test_subdirs:
                if test_dir.startswith("Test"):
                    tar_path = f"{gcs_path}/artifacts/{step_name}/{inner_subdir}/artifacts/{test_dir}/hostedcluster.tar"
                    results.append((test_dir, tar_path))
                    logger.info(f"Found hostedcluster dump: {step_name}/{inner_subdir}/artifacts/{test_dir}/hostedcluster.tar")

    return results


def extract_tgz(tar_path, dest_dir):
    """Extract tar (gzip compressed) archive."""
    try:
        logger.info(f"Extracting: {tar_path} to {dest_dir}")
        dest_dir.mkdir(parents=True, exist_ok=True)

        try:
            with tarfile.open(tar_path, "r:gz") as tar:
                tar.extractall(path=dest_dir)
        except tarfile.ReadError:
            with tarfile.open(tar_path, "r:") as tar:
                tar.extractall(path=dest_dir)

        logger.info(f"Extracted successfully to: {dest_dir}")
        tar_path.unlink()
        return True
    except (tarfile.TarError, OSError) as e:
        logger.warning(f"Extraction failed: {e}. Keeping tar file for inspection.")
        return False


def write_agents_md(output_dir):
    """
    Write AGENTS.md to the output directory for AI agent context.
    Only overwrites if the existing file was created by this tool.
    """
    agents_md_path = output_dir / "AGENTS.md"

    if agents_md_path.exists():
        try:
            existing_content = agents_md_path.read_text()
            if _AGENTS_MD_SIGNATURE not in existing_content:
                logger.warning(
                    f"AGENTS.md already exists at {agents_md_path} and was not created by this tool. "
                    "Skipping to avoid overwriting user content."
                )
                return False
        except OSError as e:
            logger.warning(f"Could not read existing AGENTS.md: {e}")
            return False

    try:
        content = _AGENTS_MD_CONTENT.format(signature=_AGENTS_MD_SIGNATURE)
        agents_md_path.write_text(content)
        logger.info(f"Wrote AGENTS.md to: {agents_md_path}")
        return True
    except OSError as e:
        logger.warning(f"Failed to write AGENTS.md: {e}")
        return False


def write_build_metadata(build, build_dir, prow_base_url):
    """Write metadata JSON file for a build."""
    refs = build.get("Refs") or {}
    pulls = refs.get("pulls", [])
    spyglass_link = build.get("SpyglassLink", "")

    metadata = {
        "build_id": build.get("ID"),
        "execution_date": build.get("Started"),
        "prow_job_link": f"{prow_base_url}{spyglass_link}" if spyglass_link else None,
        "pr_link": pulls[0].get("link") if pulls else None,
        "commit_link": pulls[0].get("commit_link") if pulls else None,
    }

    metadata_path = build_dir / "build_info.json"
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)
    logger.info(f"Wrote metadata to: {metadata_path}")


def process_build(build, output_dir, prow_base_url):
    """Download artifacts for one build."""
    build_id = build.get("ID", "unknown")
    build_dir = output_dir / str(build_id)

    spyglass_link = build.get("SpyglassLink", "")

    if not spyglass_link:
        logger.warning(f"Build {build_id}: No SpyglassLink found")
        return

    logger.info(f"Processing build {build_id}")

    gcs_path = prow.spyglass_to_gcs_path(spyglass_link)
    build_dir.mkdir(parents=True, exist_ok=True)

    gcsweb_base = prow.discover_gcsweb_base(prow_base_url, spyglass_link)
    if not gcsweb_base:
        logger.warning(f"Build {build_id}: Could not discover gcsweb URL, skipping artifact downloads")
        write_build_metadata(build, build_dir, prow_base_url)
        return

    # Download junit_operator.xml
    junit_dest = build_dir / "junit_operator.xml"
    if junit_dest.exists():
        logger.info(f"Build {build_id}: junit_operator.xml already exists, skipping")
    else:
        junit_url = f"{gcsweb_base}{gcs_path}/artifacts/junit_operator.xml"
        if not http.download_artifact(junit_url, junit_dest):
            logger.warning(f"Build {build_id}: junit_operator.xml not available")

    # Download build logs and junit files for failed steps only
    logs_dir = build_dir / "build-logs"
    if logs_dir.exists():
        logger.info(f"Build {build_id}: build-logs directory already exists, skipping")
    elif junit_dest.exists():
        failures = parse_junit_operator_failures(junit_dest)
        if failures:
            count = download_failed_step_artifacts(gcs_path, gcsweb_base, failures, logs_dir)
            if count:
                logger.info(f"Build {build_id}: downloaded {count} artifact(s) for failed steps")
        else:
            logger.info(f"Build {build_id}: no failed multi-stage steps found")

    # Fetch step graph for artifact discovery
    step_graph = fetch_step_graph(gcs_path, gcsweb_base)

    if step_graph is None:
        logger.error(f"Build {build_id}: cannot discover artifacts without step graph, skipping")
    else:
        # Discover and download must-gather
        extract_dir = build_dir / "must-gather"
        if extract_dir.exists():
            logger.info(f"Build {build_id}: must-gather already exists, skipping")
        else:
            must_gather_gcs_path = discover_must_gather(gcs_path, gcsweb_base, step_graph)
            if must_gather_gcs_path:
                must_gather_url = f"{gcsweb_base}{must_gather_gcs_path}"
                tar_dest = build_dir / "must-gather.tar"
                if http.download_artifact(must_gather_url, tar_dest):
                    extract_tgz(tar_dest, extract_dir)

        # Discover and download hostedcluster dumps
        hypershift_dir = build_dir / "hypershift-dumps"
        if hypershift_dir.exists():
            logger.info(f"Build {build_id}: hypershift-dumps already exists, skipping")
        else:
            dumps = discover_hypershift_dumps(gcs_path, gcsweb_base, step_graph)
            if dumps:
                for test_name, tar_gcs_path in dumps:
                    tar_url = f"{gcsweb_base}{tar_gcs_path}"
                    tar_dest = build_dir / "hostedcluster.tar"
                    extract_dest = hypershift_dir / test_name
                    if http.download_artifact(tar_url, tar_dest):
                        extract_tgz(tar_dest, extract_dest)

    write_build_metadata(build, build_dir, prow_base_url)

    logger.info(f"Completed processing build {build_id}")
