import json
import logging
import re
import shutil
import tarfile
from pathlib import Path
from typing import Any

from .fetch_url import fetch_url, FetchError, NotFoundError
from .import_job import import_job, JobImportError

logger = logging.getLogger(__name__)


class ArtifactError(Exception):
    pass

_AGENTS_MD_SIGNATURE = "<!-- Generated by download_prow_job.py -->"

_AGENTS_MD_CONTENT = """{signature}
# Prow CI Job Artifacts

This directory contains artifacts downloaded from Prow CI jobs.

## Directory Structure

Each subdirectory is named by build ID and may contain:

- `job.json` - Job metadata including:
  - `spyglass`: Link to the Prow job page (Spyglass view)
  - `build_id`: The Prow build ID
  - `job_name`: CI job name
  - `job_type`: Job type (presubmit, postsubmit, periodic)
  - `pr_link`: GitHub PR URL (if PR job)
  - `gcs_path`: GCS bucket path for this build's artifacts
  - `gcsweb_base`: Base URL for gcsweb artifact access
  - `steps`: List of top-level CI steps, each with:
    - `name`: Step name
    - `success`: Whether the step passed
    - `steps_file`: Filename of inner steps JSON (only for multi-stage tests)

- `{{test}}.steps.json` - Inner steps for a multi-stage test, keyed by step name:
  - Each entry has `success: bool`

- `steps.json` - Symlink to the first multi-stage test's steps file

- `ci-operator-step-graph.json` - Raw step graph from ci-operator

- `build-logs/` - Artifacts for failed steps only
  - `{{step-name}}/` - One subdirectory per failed step
    - `build-log.txt` - Complete untruncated build log
    - `junit_e2e__*.xml` - Individual e2e test results (if the step produced junit output)
    - `e2e-monitor-tests__*.xml` - Monitor test results (if available)

- `must-gather/` - Extracted must-gather diagnostic data (if downloaded via --auto-must-gather or must-gather command)

- `hypershift-dumps/` - Extracted HyperShift hosted cluster dumps (if downloaded via --auto-hypershift or hypershift-dump command)
  - `TestCreateCluster/` - Dump for each test case
  - `TestNodePool_HostedCluster0/`
  - Contains pod logs, events, and resource YAMLs from the hosted control plane

## Analyzing Test Failures

1. Check `job.json` for the job link, PR context, and step list
2. Identify failed steps from `steps` in `job.json`
3. Read inner step details from `*.steps.json` files
4. Read `build-logs/{{step}}/build-log.txt` for complete failure output
5. Parse `build-logs/{{step}}/junit_e2e__*.xml` for individual e2e test failures (if available)
6. For cluster issues, examine logs in `must-gather/`

## must-gather Contents

The must-gather directory contains OpenShift cluster diagnostics:
- Pod logs from key namespaces
- Cluster operator status
- Event logs
- Resource definitions

Look for errors in `must-gather/*/logs/` and check operator status in
`must-gather/*/cluster-scoped-resources/`.
"""


def _download(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with fetch_url(url) as body:
        with open(dest, "wb") as f:
            shutil.copyfileobj(body, f)
    logger.info(f"Downloaded to: {dest}")


def _list_gcsweb_dir(url: str) -> tuple[list[str], list[str]]:
    try:
        with fetch_url(url) as body:
            html = body.read().decode()
    except NotFoundError:
        return [], []

    hrefs = re.findall(r'href="([^"]+)"', html)
    subdirs = []
    files = []
    for href in hrefs:
        name = href.rstrip("/").split("/")[-1]
        if not name or name == "..":
            continue
        if href.endswith("/"):
            subdirs.append(name)
        else:
            files.append(name)
    return subdirs, files


def download_failed_step_artifacts(gcs_path: str, gcsweb_base: str, failures: list[tuple[str, str]], logs_dir: Path) -> int:
    """
    Download build-log.txt and any junit XML files for each failed step.

    build-log.txt is at a deterministic path (no directory listing needed).
    junit files require up to 2 directory listing requests per failed step.
    """
    total = 0

    for test_name, full_step_name in failures:
        step_base = f"{gcs_path}/artifacts/{test_name}/{full_step_name}"
        dest_dir = logs_dir / full_step_name

        build_log_url = f"{gcsweb_base}{step_base}/build-log.txt"
        try:
            _download(build_log_url, dest_dir / "build-log.txt")
            total += 1
        except FetchError:
            pass

        artifacts_base = f"{step_base}/artifacts"

        try:
            junit_subdir_url = f"{gcsweb_base}{artifacts_base}/junit/"
            _, files = _list_gcsweb_dir(junit_subdir_url)
            for filename in [f for f in files if f.endswith(".xml")]:
                try:
                    _download(f"{gcsweb_base}{artifacts_base}/junit/{filename}", dest_dir / filename)
                    total += 1
                except FetchError:
                    pass
        except FetchError as e:
            logger.warning(f"Failed to list junit dir for {full_step_name}: {e}")

        try:
            artifacts_url = f"{gcsweb_base}{artifacts_base}/"
            _, root_files = _list_gcsweb_dir(artifacts_url)
            for filename in [f for f in root_files if f.startswith("junit") and f.endswith(".xml")]:
                try:
                    _download(f"{gcsweb_base}{artifacts_base}/{filename}", dest_dir / filename)
                    total += 1
                except FetchError:
                    pass
        except FetchError as e:
            logger.warning(f"Failed to list artifacts dir for {full_step_name}: {e}")

        logger.info(f"Downloaded artifacts for failed step {full_step_name}")

    return total


def discover_must_gather(job_dir: Path, gcs_path: str) -> str:
    """
    Find must-gather.tar by scanning *.steps.json files for gather-must-gather.
    Returns the full GCS path to must-gather.tar.
    Raises ArtifactError if no must-gather step is found.
    """
    for steps_file in sorted(job_dir.glob("*.steps.json")):
        if steps_file.name == "steps.json":
            continue
        test_name = steps_file.name.removesuffix(".steps.json")
        inner = json.loads(steps_file.read_text())
        if "gather-must-gather" not in inner:
            continue
        full_path = f"{gcs_path}/artifacts/{test_name}/gather-must-gather/artifacts/must-gather.tar"
        logger.info(f"Must-gather candidate: {test_name}/gather-must-gather/artifacts/must-gather.tar")
        return full_path

    raise ArtifactError("No must-gather found in any test step")


def discover_hypershift_dumps(gcs_path: str, gcsweb_base: str, steps: dict[str, Any]) -> list[tuple[str, str]]:
    """
    Find hostedcluster.tar files from steps running the HyperShift test binary.
    Uses step hierarchy to identify relevant steps via [input:hypershift-tests]
    dependency, and inner step names to avoid directory listing where possible.
    Returns list of (test_dir_name, gcs_tar_path) tuples.
    Raises ArtifactError if no hypershift test steps or dumps are found.
    """
    hypershift_tests = {
        name: info for name, info in steps.items()
        if "[input:hypershift-tests]" in (info.get("dependencies") or [])
    }

    if not hypershift_tests:
        raise ArtifactError("No HyperShift test steps found in build")

    logger.info(f"Found HyperShift test steps: {list(hypershift_tests)}")
    results = []

    for test_name, step_info in hypershift_tests.items():
        inner_steps = step_info.get("inner_steps", {})
        if not inner_steps:
            inner_step_names, _ = _list_gcsweb_dir(
                f"{gcsweb_base}{gcs_path}/artifacts/{test_name}/"
            )
        else:
            inner_step_names = list(inner_steps)

        for inner_step in inner_step_names:
            inner_artifacts_url = f"{gcsweb_base}{gcs_path}/artifacts/{test_name}/{inner_step}/artifacts/"
            test_subdirs, _ = _list_gcsweb_dir(inner_artifacts_url)

            for test_dir in test_subdirs:
                if test_dir.startswith("Test"):
                    tar_path = f"{gcs_path}/artifacts/{test_name}/{inner_step}/artifacts/{test_dir}/hostedcluster.tar"
                    results.append((test_dir, tar_path))
                    logger.info(f"Found hostedcluster dump: {test_name}/{inner_step}/artifacts/{test_dir}/hostedcluster.tar")

    if not results:
        raise ArtifactError("No hypershift dumps found in HyperShift test steps")

    return results


def extract_tgz(tar_path: Path, dest_dir: Path) -> None:
    """Extract tar (gzip compressed) archive.
    Raises tarfile.TarError or OSError on extraction failure.
    On failure, the tar file is kept for inspection (unlink only runs on success).
    """
    logger.info(f"Extracting: {tar_path} to {dest_dir}")
    dest_dir.mkdir(parents=True, exist_ok=True)

    try:
        with tarfile.open(tar_path, "r:gz") as tar:
            tar.extractall(path=dest_dir)
    except tarfile.ReadError:
        with tarfile.open(tar_path, "r:") as tar:
            tar.extractall(path=dest_dir)

    logger.info(f"Extracted successfully to: {dest_dir}")
    tar_path.unlink()


def download_must_gather(job_dir: Path, gcs_path: str, gcsweb_base: str, step_name: str | None = None) -> None:
    """Download and extract must-gather. No-op if already exists.
    Raises ArtifactError if must-gather cannot be found, downloaded, or extracted.
    """
    extract_dir = job_dir / "must-gather"
    if extract_dir.exists():
        logger.info("must-gather already exists, skipping")
        return

    if step_name:
        must_gather_gcs_path = f"{gcs_path}/artifacts/{step_name}/gather-must-gather/artifacts/must-gather.tar"
    else:
        must_gather_gcs_path = discover_must_gather(job_dir, gcs_path)

    must_gather_url = f"{gcsweb_base}{must_gather_gcs_path}"
    tar_dest = job_dir / "must-gather.tar"
    try:
        _download(must_gather_url, tar_dest)
    except FetchError as e:
        raise ArtifactError(f"Failed to download must-gather: {e}") from e

    try:
        extract_tgz(tar_dest, extract_dir)
    except (tarfile.TarError, OSError) as e:
        raise ArtifactError(f"Failed to extract must-gather: {e}") from e


def _build_hypershift_steps(job_dir: Path) -> dict[str, Any]:
    """Build step hierarchy with dependencies for hypershift detection.
    Reads the saved step graph and *.steps.json files.
    """
    step_graph_path = job_dir / "ci-operator-step-graph.json"
    if not step_graph_path.exists():
        raise ArtifactError("Step graph not available for hypershift detection")
    step_graph = json.loads(step_graph_path.read_text())

    steps: dict[str, Any] = {}
    for s in step_graph:
        name = s.get("name", "")
        if name.startswith("["):
            continue
        steps[name] = {
            "dependencies": s.get("dependencies"),
            "inner_steps": {},
        }

    for steps_file in job_dir.glob("*.steps.json"):
        if steps_file.name == "steps.json":
            continue
        test_name = steps_file.name.removesuffix(".steps.json")
        if test_name in steps:
            steps[test_name]["inner_steps"] = json.loads(steps_file.read_text())

    return steps


def download_hypershift_dumps(job_dir: Path, gcs_path: str, gcsweb_base: str, step_name: str | None = None) -> None:
    """Download and extract hypershift dumps. No-op if already exists.
    Raises ArtifactError if no dumps can be found.
    """
    hypershift_dir = job_dir / "hypershift-dumps"
    if hypershift_dir.exists():
        logger.info("hypershift-dumps already exists, skipping")
        return

    steps = _build_hypershift_steps(job_dir)

    if step_name:
        if step_name not in steps:
            raise ArtifactError(f"Step '{step_name}' not found in build steps")
        filtered_steps = {step_name: steps[step_name]}
    else:
        filtered_steps = steps

    if not filtered_steps:
        raise ArtifactError("No step data available for hypershift dump discovery")

    dumps = discover_hypershift_dumps(gcs_path, gcsweb_base, filtered_steps)

    for test_name, tar_gcs_path in dumps:
        tar_url = f"{gcsweb_base}{tar_gcs_path}"
        tar_dest = job_dir / "hostedcluster.tar"
        extract_dest = hypershift_dir / test_name
        try:
            _download(tar_url, tar_dest)
        except FetchError as e:
            logger.warning(f"Failed to download {test_name} dump: {e}")
            continue
        try:
            extract_tgz(tar_dest, extract_dest)
        except (tarfile.TarError, OSError) as e:
            logger.warning(f"Failed to extract {test_name} dump: {e}")


def write_agents_md(output_dir: Path) -> None:
    """
    Write AGENTS.md to the output directory for AI agent context.
    Only overwrites if the existing file was created by this tool.
    Raises OSError on file read/write failures.
    """
    agents_md_path = output_dir / "AGENTS.md"

    if agents_md_path.exists():
        existing_content = agents_md_path.read_text()
        if _AGENTS_MD_SIGNATURE not in existing_content:
            logger.warning(
                f"AGENTS.md already exists at {agents_md_path} and was not created by this tool. "
                "Skipping to avoid overwriting user content."
            )
            return

    content = _AGENTS_MD_CONTENT.format(signature=_AGENTS_MD_SIGNATURE)
    agents_md_path.write_text(content)
    logger.info(f"Wrote AGENTS.md to: {agents_md_path}")


def _collect_failures(job_dir: Path, job: dict[str, Any]) -> list[tuple[str, str]]:
    """Collect failed inner steps from *.steps.json files."""
    failures = []
    for step in job["steps"]:
        if "steps_file" not in step:
            continue
        inner = json.loads((job_dir / step["steps_file"]).read_text())
        for inner_name, inner_info in inner.items():
            if not inner_info["success"]:
                failures.append((step["name"], inner_name))
    return failures


def process_build(spyglass_url: str, output_dir: Path,
                  auto_must_gather: bool = False, auto_hypershift: bool = False) -> None:
    """Import and download artifacts for one build."""
    try:
        job_dir = import_job(spyglass_url, output_dir)
    except JobImportError as e:
        logger.warning(f"Failed to import job: {e}")
        return

    job = json.loads((job_dir / "job.json").read_text())
    build_id = job["build_id"]
    gcs_path = job["gcs_path"]
    gcsweb_base = job["gcsweb_base"]

    logs_dir = job_dir / "build-logs"
    if logs_dir.exists():
        logger.info(f"Build {build_id}: build-logs directory already exists, skipping")
    else:
        failures = _collect_failures(job_dir, job)
        if failures:
            count = download_failed_step_artifacts(gcs_path, gcsweb_base, failures, logs_dir)
            if count:
                logger.info(f"Build {build_id}: downloaded {count} artifact(s) for failed steps")
        else:
            logger.info(f"Build {build_id}: no failed multi-stage steps found")

    if auto_must_gather:
        try:
            download_must_gather(job_dir, gcs_path, gcsweb_base)
        except ArtifactError as e:
            logger.warning(f"Build {build_id}: {e}")

    if auto_hypershift:
        try:
            download_hypershift_dumps(job_dir, gcs_path, gcsweb_base)
        except ArtifactError as e:
            logger.warning(f"Build {build_id}: {e}")

    logger.info(f"Completed processing build {build_id}")
