import json
import logging
import re
import tarfile
import xml.etree.ElementTree as ET

import requests

from . import http
from . import prow

logger = logging.getLogger(__name__)

_AGENTS_MD_SIGNATURE = "<!-- Generated by download_prow_job.py -->"

_AGENTS_MD_CONTENT = """{signature}
# Prow CI Job Artifacts

This directory contains artifacts downloaded from Prow CI jobs.

## Directory Structure

Each subdirectory is named by build ID and may contain:

- `build_info.json` - Build metadata including:
  - `build_id`: The Prow build ID
  - `execution_date`: When the build ran (ISO 8601)
  - `prow_job_link`: Link to the Prow job page (Spyglass view)
  - `pr_link`: GitHub PR URL (if PR job)
  - `commit_link`: GitHub commit URL being tested
  - `gcs_path`: GCS bucket path for this build's artifacts
  - `gcsweb_base`: Base URL for gcsweb artifact access
  - `steps`: Hierarchical CI step structure keyed by test name, each with:
    - `failed`, `started_at`, `finished_at`, `duration_seconds`, `dependencies`
    - `inner_steps`: dict of inner step names to `{{failed: bool}}`

- `ci-operator-step-graph.json` - Raw step graph from ci-operator

- `junit_operator.xml` - JUnit XML test results from the CI operator

- `build-logs/` - Artifacts for failed steps only
  - `{{step-name}}/` - One subdirectory per failed step
    - `build-log.txt` - Complete untruncated build log
    - `junit_e2e__*.xml` - Individual e2e test results (if the step produced junit output)
    - `e2e-monitor-tests__*.xml` - Monitor test results (if available)

- `must-gather/` - Extracted must-gather diagnostic data (if downloaded via --auto-must-gather or must-gather command)

- `hypershift-dumps/` - Extracted HyperShift hosted cluster dumps (if downloaded via --auto-hypershift or hypershift-dump command)
  - `TestCreateCluster/` - Dump for each test case
  - `TestNodePool_HostedCluster0/`
  - Contains pod logs, events, and resource YAMLs from the hosted control plane

## Analyzing Test Failures

1. Check `build_info.json` for the job link, PR context, and step hierarchy
2. Identify failed steps from `steps` in `build_info.json`, or parse `junit_operator.xml`
3. Read `build-logs/{{step}}/build-log.txt` for complete failure output
4. Parse `build-logs/{{step}}/junit_e2e__*.xml` for individual e2e test failures (if available)
5. For cluster issues, examine logs in `must-gather/`

## must-gather Contents

The must-gather directory contains OpenShift cluster diagnostics:
- Pod logs from key namespaces
- Cluster operator status
- Event logs
- Resource definitions

Look for errors in `must-gather/*/logs/` and check operator status in
`must-gather/*/cluster-scoped-resources/`.
"""


def fetch_step_graph(gcs_path, gcsweb_base, dest):
    """Download and parse ci-operator-step-graph.json.
    Saves the raw JSON to dest. Returns parsed list of step dicts, or None.
    """
    if dest.exists():
        try:
            return json.loads(dest.read_text())
        except (json.JSONDecodeError, OSError) as e:
            logger.warning(f"Failed to read cached step graph: {e}")

    url = f"{gcsweb_base}{gcs_path}/artifacts/ci-operator-step-graph.json"
    try:
        logger.info(f"Fetching step graph: {url}")
        response = http.session_get(url, timeout=30)
        if response.status_code == 404:
            logger.error("Step graph not found (404)")
            return None
        response.raise_for_status()
        parsed = json.loads(response.text)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(response.text)
        return parsed
    except requests.RequestException as e:
        logger.error(f"Failed to fetch step graph: {e}")
        return None
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse step graph JSON: {e}")
        return None


def parse_junit_operator_steps(junit_path):
    """
    Parse junit_operator.xml to extract all multi-stage test steps.
    Returns nested dict: {test_name: {inner_step: {"failed": bool}, ...}, ...}

    Test case names follow the pattern:
      "Run multi-stage test {test_name} - {test_name}-{inner_step} container test"

    The artifact directory uses inner_step (prefix stripped), not the full step name.
    """
    try:
        tree = ET.parse(junit_path)
    except (ET.ParseError, OSError) as e:
        logger.warning(f"Failed to parse {junit_path}: {e}")
        return {}

    steps = {}

    for tc in tree.getroot().iter("testcase"):
        name = tc.get("name", "")
        m = re.match(r"Run multi-stage test (\S+) - (\S+) container test", name)
        if not m:
            continue
        test_name, full_step = m.group(1), m.group(2)
        prefix = test_name + "-"
        inner_step = full_step[len(prefix):] if full_step.startswith(prefix) else full_step
        failed = tc.find("failure") is not None
        steps.setdefault(test_name, {})[inner_step] = {"failed": failed}

    return steps


def build_step_hierarchy(junit_steps, step_graph):
    """
    Combine step graph metadata with junit inner steps into a hierarchical structure.

    Args:
        junit_steps: dict from parse_junit_operator_steps, or {} if unavailable.
        step_graph: list of step dicts from fetch_step_graph, or None if unavailable.

    Returns dict keyed by test name, each with metadata and inner_steps.
    """
    result = {}

    if step_graph is not None:
        for s in step_graph:
            name = s.get("name", "")
            if name.startswith("["):
                continue
            duration = s.get("duration")
            result[name] = {
                "failed": s.get("failed", False),
                "started_at": s.get("started_at"),
                "finished_at": s.get("finished_at"),
                "duration_seconds": duration / 1_000_000_000 if duration else None,
                "dependencies": s.get("dependencies"),
                "inner_steps": {},
            }

    for test_name, inner_dict in junit_steps.items():
        if test_name in result:
            result[test_name]["inner_steps"] = inner_dict
        else:
            result[test_name] = {
                "failed": any(v.get("failed") for v in inner_dict.values()),
                "started_at": None,
                "finished_at": None,
                "duration_seconds": None,
                "dependencies": None,
                "inner_steps": inner_dict,
            }

    return result


def download_failed_step_artifacts(gcs_path, gcsweb_base, failures, logs_dir):
    """
    Download build-log.txt and any junit XML files for each failed step.

    build-log.txt is at a deterministic path (no directory listing needed).
    junit files require up to 2 directory listing requests per failed step.
    """
    total = 0

    for test_name, full_step_name in failures:
        step_base = f"{gcs_path}/artifacts/{test_name}/{full_step_name}"
        dest_dir = logs_dir / full_step_name

        build_log_url = f"{gcsweb_base}{step_base}/build-log.txt"
        if http.download_artifact(build_log_url, dest_dir / "build-log.txt"):
            total += 1

        artifacts_base = f"{step_base}/artifacts"

        junit_subdir_url = f"{gcsweb_base}{artifacts_base}/junit/"
        _, files = http.list_gcsweb_dir(junit_subdir_url)
        for filename in [f for f in files if f.endswith(".xml")]:
            if http.download_artifact(f"{gcsweb_base}{artifacts_base}/junit/{filename}", dest_dir / filename):
                total += 1

        artifacts_url = f"{gcsweb_base}{artifacts_base}/"
        _, root_files = http.list_gcsweb_dir(artifacts_url)
        for filename in [f for f in root_files if f.startswith("junit") and f.endswith(".xml")]:
            if http.download_artifact(f"{gcsweb_base}{artifacts_base}/{filename}", dest_dir / filename):
                total += 1

        logger.info(f"Downloaded artifacts for failed step {full_step_name}")

    return total


def discover_must_gather(gcs_path, steps):
    """
    Find must-gather.tar using step hierarchy.
    Returns the full GCS path to must-gather.tar if found, None otherwise.
    """
    for test_name, step_info in steps.items():
        inner_steps = step_info.get("inner_steps", {})
        if inner_steps:
            if "gather-must-gather" not in inner_steps:
                continue
        full_path = f"{gcs_path}/artifacts/{test_name}/gather-must-gather/artifacts/must-gather.tar"
        logger.info(f"Must-gather candidate: {test_name}/gather-must-gather/artifacts/must-gather.tar")
        return full_path

    logger.info("No must-gather found in any test step")
    return None


def discover_hypershift_dumps(gcs_path, gcsweb_base, steps):
    """
    Find hostedcluster.tar files from steps running the HyperShift test binary.
    Uses step hierarchy to identify relevant steps via [input:hypershift-tests]
    dependency, and inner step names to avoid directory listing where possible.
    Returns list of (test_dir_name, gcs_tar_path) tuples, or empty list.
    """
    hypershift_tests = {
        name: info for name, info in steps.items()
        if "[input:hypershift-tests]" in (info.get("dependencies") or [])
    }

    if not hypershift_tests:
        return []

    logger.info(f"Found HyperShift test steps: {list(hypershift_tests)}")
    results = []

    for test_name, step_info in hypershift_tests.items():
        inner_steps = step_info.get("inner_steps", {})
        if not inner_steps:
            inner_step_names, _ = http.list_gcsweb_dir(
                f"{gcsweb_base}{gcs_path}/artifacts/{test_name}/"
            )
        else:
            inner_step_names = list(inner_steps)

        for inner_step in inner_step_names:
            inner_artifacts_url = f"{gcsweb_base}{gcs_path}/artifacts/{test_name}/{inner_step}/artifacts/"
            test_subdirs, _ = http.list_gcsweb_dir(inner_artifacts_url)

            for test_dir in test_subdirs:
                if test_dir.startswith("Test"):
                    tar_path = f"{gcs_path}/artifacts/{test_name}/{inner_step}/artifacts/{test_dir}/hostedcluster.tar"
                    results.append((test_dir, tar_path))
                    logger.info(f"Found hostedcluster dump: {test_name}/{inner_step}/artifacts/{test_dir}/hostedcluster.tar")

    return results


def extract_tgz(tar_path, dest_dir):
    """Extract tar (gzip compressed) archive."""
    try:
        logger.info(f"Extracting: {tar_path} to {dest_dir}")
        dest_dir.mkdir(parents=True, exist_ok=True)

        try:
            with tarfile.open(tar_path, "r:gz") as tar:
                tar.extractall(path=dest_dir)
        except tarfile.ReadError:
            with tarfile.open(tar_path, "r:") as tar:
                tar.extractall(path=dest_dir)

        logger.info(f"Extracted successfully to: {dest_dir}")
        tar_path.unlink()
        return True
    except (tarfile.TarError, OSError) as e:
        logger.warning(f"Extraction failed: {e}. Keeping tar file for inspection.")
        return False


def write_agents_md(output_dir):
    """
    Write AGENTS.md to the output directory for AI agent context.
    Only overwrites if the existing file was created by this tool.
    """
    agents_md_path = output_dir / "AGENTS.md"

    if agents_md_path.exists():
        try:
            existing_content = agents_md_path.read_text()
            if _AGENTS_MD_SIGNATURE not in existing_content:
                logger.warning(
                    f"AGENTS.md already exists at {agents_md_path} and was not created by this tool. "
                    "Skipping to avoid overwriting user content."
                )
                return False
        except OSError as e:
            logger.warning(f"Could not read existing AGENTS.md: {e}")
            return False

    try:
        content = _AGENTS_MD_CONTENT.format(signature=_AGENTS_MD_SIGNATURE)
        agents_md_path.write_text(content)
        logger.info(f"Wrote AGENTS.md to: {agents_md_path}")
        return True
    except OSError as e:
        logger.warning(f"Failed to write AGENTS.md: {e}")
        return False


def write_build_metadata(build, build_dir, prow_base_url, steps=None,
                         gcs_path=None, gcsweb_base=None):
    """Write metadata JSON file for a build."""
    refs = build.get("Refs") or {}
    pulls = refs.get("pulls", [])
    spyglass_link = build.get("SpyglassLink", "")

    metadata = {
        "build_id": build.get("ID"),
        "execution_date": build.get("Started"),
        "prow_job_link": f"{prow_base_url}{spyglass_link}" if spyglass_link else None,
        "pr_link": pulls[0].get("link") if pulls else None,
        "commit_link": pulls[0].get("commit_link") if pulls else None,
        "gcs_path": gcs_path,
        "gcsweb_base": gcsweb_base,
    }

    if steps is not None:
        metadata["steps"] = steps

    metadata_path = build_dir / "build_info.json"
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)
    logger.info(f"Wrote metadata to: {metadata_path}")


def process_build(build, output_dir, prow_base_url,
                  auto_must_gather=False, auto_hypershift=False):
    """Download artifacts for one build."""
    build_id = build.get("ID", "unknown")
    build_dir = output_dir / str(build_id)

    spyglass_link = build.get("SpyglassLink", "")

    if not spyglass_link:
        logger.warning(f"Build {build_id}: No SpyglassLink found")
        return

    logger.info(f"Processing build {build_id}")

    gcs_path = prow.spyglass_to_gcs_path(spyglass_link)
    build_dir.mkdir(parents=True, exist_ok=True)

    gcsweb_base = prow.discover_gcsweb_base(prow_base_url, spyglass_link)
    if not gcsweb_base:
        logger.warning(f"Build {build_id}: Could not discover gcsweb URL, skipping artifact downloads")
        write_build_metadata(build, build_dir, prow_base_url, gcs_path=gcs_path)
        return

    # Download junit_operator.xml
    junit_dest = build_dir / "junit_operator.xml"
    if junit_dest.exists():
        logger.info(f"Build {build_id}: junit_operator.xml already exists, skipping download")
    else:
        junit_url = f"{gcsweb_base}{gcs_path}/artifacts/junit_operator.xml"
        if not http.download_artifact(junit_url, junit_dest):
            logger.warning(f"Build {build_id}: junit_operator.xml not available")

    # Fetch step graph (saved as artifact)
    step_graph_dest = build_dir / "ci-operator-step-graph.json"
    step_graph = fetch_step_graph(gcs_path, gcsweb_base, step_graph_dest)

    # Build step hierarchy from junit + step graph
    junit_steps = {}
    if junit_dest.exists():
        junit_steps = parse_junit_operator_steps(junit_dest)
    steps = build_step_hierarchy(junit_steps, step_graph)

    # Write build_info.json with step hierarchy
    write_build_metadata(build, build_dir, prow_base_url, steps=steps,
                         gcs_path=gcs_path, gcsweb_base=gcsweb_base)

    # Download build logs and junit files for failed steps
    logs_dir = build_dir / "build-logs"
    if logs_dir.exists():
        logger.info(f"Build {build_id}: build-logs directory already exists, skipping")
    else:
        failures = [
            (test_name, inner_step)
            for test_name, step_info in steps.items()
            for inner_step, inner_info in step_info.get("inner_steps", {}).items()
            if inner_info.get("failed")
        ]
        if failures:
            count = download_failed_step_artifacts(gcs_path, gcsweb_base, failures, logs_dir)
            if count:
                logger.info(f"Build {build_id}: downloaded {count} artifact(s) for failed steps")
        else:
            logger.info(f"Build {build_id}: no failed multi-stage steps found")

    if (auto_must_gather or auto_hypershift) and not steps:
        logger.warning(f"Build {build_id}: no step data available, skipping artifact discovery")
    else:
        if auto_must_gather:
            extract_dir = build_dir / "must-gather"
            if extract_dir.exists():
                logger.info(f"Build {build_id}: must-gather already exists, skipping")
            else:
                must_gather_gcs_path = discover_must_gather(gcs_path, steps)
                if must_gather_gcs_path:
                    must_gather_url = f"{gcsweb_base}{must_gather_gcs_path}"
                    tar_dest = build_dir / "must-gather.tar"
                    if http.download_artifact(must_gather_url, tar_dest):
                        extract_tgz(tar_dest, extract_dir)

        if auto_hypershift:
            hypershift_dir = build_dir / "hypershift-dumps"
            if hypershift_dir.exists():
                logger.info(f"Build {build_id}: hypershift-dumps already exists, skipping")
            else:
                dumps = discover_hypershift_dumps(gcs_path, gcsweb_base, steps)
                if dumps:
                    for test_name, tar_gcs_path in dumps:
                        tar_url = f"{gcsweb_base}{tar_gcs_path}"
                        tar_dest = build_dir / "hostedcluster.tar"
                        extract_dest = hypershift_dir / test_name
                        if http.download_artifact(tar_url, tar_dest):
                            extract_tgz(tar_dest, extract_dest)

    logger.info(f"Completed processing build {build_id}")
